### ISSUE TITLE
Getting invalid version error

### ISSUE THREAD

**Issue by chsharma27** [megagonlabs/doduo#5]
When executing "$ python doduo/train_multi.py --tasks turl turl_re-colpair --max_length 32 --batch_size 16", getting the following error. Could you please help?
Traceback (most recent call last):
  File "doduo/train_multi.py", line 14, in <module>
    from transformers import BertTokenizer, BertForSequenceClassification, BertConfig
  File "/data/conceptdrift/anaconda3/envs/doduo/bin/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/data/conceptdrift/anaconda3/envs/doduo/bin/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/data/conceptdrift/anaconda3/envs/doduo/bin/transformers/utils/versions.py", line 101, in require_version_core
    return require_version(requirement, hint)
  File "/data/conceptdrift/anaconda3/envs/doduo/bin/transformers/utils/versions.py", line 92, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "/data/conceptdrift/anaconda3/envs/doduo/bin/packaging/version.py", line 52, in parse
    return Version(version)
  File "/data/conceptdrift/anaconda3/envs/doduo/bin/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

**Comment by maltarawy** [comment]
pip install packaging==20.0

**Comment by Omadzze** [comment]
pip install packaging==21.3

https://github.com/CompVis/latent-diffusion/issues/207#issuecomment-1378716088
